blank_issues_enabled: true
contact_links:
  - name: Discord Chat
    url: https://discord.gg/HCYpT5QHQR
    about: Ask questions and discuss ideas with other users real-time
  - name: "Discussions"
    url: "https://github.com/tsrx-org/tsrx/discussions"
    about: "Ask questions and discuss ideas with the community"
