id = "tsrx"
name = "TSRX"
description = "TSRX language support with LSP and Tree-sitter syntax highlighting. TSRX is a TypeScript superset that compiles to Ripple, React, Solid, and Preact."
version = "0.0.84"
schema_version = 1
authors = ["Dominic Gannaway <trueadm@users.noreply.github.com>"]
repository = "https://github.com/Ripple-TS/ripple"

[grammars.ripple]
repository = "https://github.com/Ripple-TS/ripple"
rev = "ba83189e5e7d4b8e63c3a523fdd808d365bf7662"
path = "grammars/tree-sitter"

[language_servers.ripple-language-server]
name = "Ripple Language Server"
languages = ["TSRX"]

[language_servers.ripple-language-server.language_ids]
"TSRX" = "ripple"
