on: workflow_dispatch

name: Publish VSC Extension (Manual)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install deps w/ pnpm
        working-directory: ./packages/vscode-plugin
        run: pnpm install --frozen-lockfile

      - name: Build VSIX
        working-directory: ./packages/vscode-plugin
        run: pnpm run build-and-package

      - name: Upload VSIX
        uses: actions/upload-artifact@v7
        with:
          name: vscode-plugin VSIX
          path: ./packages/vscode-plugin/vscode-plugin.vsix
          if-no-files-found: error

  publish-vsm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download VSIX
        uses: actions/download-artifact@v7
        with:
          name: vscode-plugin VSIX
          path: ./packages/vscode-plugin

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install deps w/ pnpm
        run: pnpm install --frozen-lockfile

      - name: Publish to VSM
        working-directory: ./packages/vscode-plugin
        run: pnpm exec vsce publish -i *.vsix
        env:
          VSCE_PAT: ${{ secrets.VSM_TOKEN }}

  publish-ovsx:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download VSIX
        uses: actions/download-artifact@v7
        with:
          name: vscode-plugin VSIX
          path: ./packages/vscode-plugin

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install deps w/ pnpm
        run: pnpm install --frozen-lockfile

      - name: Publish to OVSX
        working-directory: ./packages/vscode-plugin
        run: pnpm exec ovsx publish *.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
